### ISSUE TITLE
Instructions for running client-side, or clarification that it only works server-side.

### ISSUE THREAD

**Issue by Reklino** [michaeltaranto/less-vars-to-js#5]
Hey peeps. I'm looking to use this in an project that uses webpack to build a client-side react app. Is this possible using the node 'fs' module?

I'm getting conflicting results form searches, but it seems like 'fs' is usually reserved for server-side node apps. The react example in the readme makes me think you're using it client-side though. I know this isn't necessary related to the project itself, but I'm sure it's something others have or will run into as well when trying to use this.

Any help/clarification is much appreciated. Great project :).

**Comment by michaeltaranto** [comment]
Not sure that use case is applicable, you're not shipping your LESS files to the client? `fs` is a node module for accessing the file system not available in the browser, so yep it's server side only.

If you wanted to generate a client side build that consumed these less variables, you could use webpack to require the raw less file (not pass it through css-loader) and then pass the raw string value into this function. That way you are extracting the variables and baking them into your client side code at build time as an object.

Does that make sense?

**Comment by michaeltaranto** [comment]
Closing for now

**Comment by Reklino** [comment]
@michaeltaranto that makes total sense 👍. I'll play around with that.
