### ISSUE TITLE
Commented out variables still end up in the output

### ISSUE THREAD

**Issue by 0x80** [michaeltaranto/less-vars-to-js#7]
This was a major source of confusion for me. 

If I comment out something in my less file, the variables still end up in the output. So less-vars-to-js seems to basically ignore them all together.

This goes for /* */ blocks and // inline comments.

**Comment by 0x80** [comment]
```javascript
export default sheet => {
  const lessVars = {};
  const matches = sheet.match(/@(.*:[^;]*)/g) || [];

  matches.forEach(variable => {
    const definition = variable.split(/:\s*/);
    lessVars[definition[0].replace(/['"]+/g, '').trim()] = definition[1];
  });

  return lessVars;
};
```

No wonder

**Comment by 0x80** [comment]
Maybe use this for parsing? https://github.com/mrmlnc/less-symbols-parser

**Comment by michaeltaranto** [comment]
Sorry this was super quick to solve a particular problem. I agree that there are a heap of better ways to solve this just not the highest priority at the moment. If you get a sec and can throw together i PR i'll have a look.

**Comment by bryanberger** [comment]
I quickly hacked together a way to preserve newlines and comments for a project. I opted to export it as a string instead of as a json object since i'm basically writing it to a file directly.

_not sure if this is useful for anyone else_

![screen shot 2017-11-21 at 3 47 59 pm](https://user-images.githubusercontent.com/940022/33095962-651f804c-ced3-11e7-9840-65a2209f715d.png)


```
var ret = ""
  var lines = sheet.toString().split("\n")

  lines.map((line, i) => {
    // is it a variable?
    var matches = line.match(/^@(.*:[^;]*)/g) || []
    if(matches.length > 0) {
      matches.forEach(variable => {
        var definition = variable.split(/:\s*/)
        ret += "'" + definition[0].replace(/['"]+/g, '').trim() + "': '" + definition.splice(1) + "', \n"
      })
    } else {
      // no, so just print it (so we can preserve new lines and comments)
      ret += (lines[i+1]) ? line + "\n" : line
    }
  })

  return ret
```

**Comment by 0x80** [comment]
@bryanberger Thanks. As a quick fix this will do for me as well. I don't have time to work on a proper solution at the moment.

**Comment by jean343** [comment]
I have forked this repo and added a few features, you could try `less-vars-to-json`.

**Comment by michaeltaranto** [comment]
Good stuff! If you want to PR anything back in I'm open to it, but totally up to you as I'm not actively working on this.

**Comment by jean343** [comment]
Thanks,

I would prefer to make a PR as it would fix `less-vars-loader` as well.
I need to have the object keys without the character `@`, would you think the best solution is to pass an object parameter?

**Comment by michaeltaranto** [comment]
Great. Sounds good. Thanks for your work, i'll give it a look over.

**Comment by jean343** [comment]
Did you prefer if I make the options the defaults, or keep those options?
